version: '3'

services:
  celery-beat:
    build: .
    environment:
      TZ: "Europe/Bucharest"
    links:
      - my-rabbitmq:rabbitmq-inst
    env_file:
      - .env
    command: poetry run celery -A celery_ship beat --broker=amqp://guest:guest@rabbitmq-inst:5672// -l info
    depends_on:
      - my-rabbitmq
  celery-worker:
    build: .
    environment:
      TZ: "Europe/Bucharest"
    links:
      - my-rabbitmq:rabbitmq-inst
    env_file:
      - .env
    command: poetry run celery -A celery_ship worker --broker=amqp://guest:guest@rabbitmq-inst:5672// -l info
    depends_on:
      - my-rabbitmq
  celery-flower:
    build: .
    environment:
      TZ: "Europe/Bucharest"
    ports:
      - "5555:5555"
    links:
      - my-rabbitmq:rabbitmq-inst
    env_file:
      - .env
    command: poetry run celery flower -A celery_ship --broker_api=http://rabbitmq-inst:15672/api/ --broker=amqp://guest:guest@rabbitmq-inst:5672// --info
    depends_on:
      - my-rabbitmq
  my-rabbitmq:
    image: rabbitmq:3.8.3-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      TZ: "Europe/Bucharest"
    ports:
      - "15672:15672"
      - "5672:5672"
