# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='deneb',
    version='2.2.4',
    description='deneb project',
    python_requires='==3.*,>=3.7.0',
    author='DTailor',
    author_email='dann.croitoru@gmail.com',
    license='MIT',
    packages=[
        'deneb', 'deneb.chatbot', 'deneb.db', 'deneb.spotify', 'deneb.workers'
    ],
    package_dir={"": "."},
    package_data={
        "deneb": [
            ".mypy_cache/3.7/*.json", ".mypy_cache/3.7/collections/*.json",
            ".mypy_cache/3.7/importlib/*.json", ".mypy_cache/3.7/json/*.json",
            ".mypy_cache/3.7/logging/*.json", ".mypy_cache/3.7/os/*.json"
        ]
    },
    install_requires=[
        'aiohttp==3.*,>=3.6.2', 'arrow==0.*,>=0.15.5', 'asyncpg==0.*,>=0.20.1',
        'celery==4.*,>=4.4.2', 'click==7.*,>=7.0.0', 'flower==0.*,>=0.9.4',
        'logzero==1.*,>=1.5.0', 'pypika==0.37.1', 'python-dotenv==0.*,>=0.12.0',
        'pytz==2019.*,>=2019.3.0', 'sentry-sdk==0.*,>=0.14.2',
        'spotipy==2.*,>=2.9.0', 'sqlalchemy==1.*,>=1.3.13',
        'tortoise-orm==0.*,>=0.15.18', 'uvloop==0.*,>=0.14.0'
    ],
    extras_require={
        "dev": [
            "aiomock==0.*,>=0.1.0", "alembic==1.*,>=1.4.1",
            "black==19.*,>=19.10.0.b0", "coverage==5.*,>=5.0.3",
            "fabric==2.*,>=2.5.0", "ipdb==0.*,>=0.13.2",
            "ipython==7.*,>=7.13.0", "isort==4.*,>=4.3.21",
            "mypy==0.*,>=0.761.0", "psycopg2-binary==2.*,>=2.8.4",
            "pyinstrument==3.*,>=3.1.3", "pylama==7.*,>=7.7.1",
            "pytest==5.*,>=5.3.5", "pytest-asyncio==0.*,>=0.10.0",
            "pytest-cov==2.*,>=2.8.1", "pytest-mock==3.*,>=3.1.0",
            "snakeviz==2.*,>=2.0.1", "vulture==1.*,>=1.3.0"
        ]
    },
)
