version: 2.1

executors:
  py-executor:
    docker:
      - image: circleci/python:3.8.5

jobs:
  build:
    executor: py-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - pip-packages-{{ .Branch }}-{{ checksum "poetry.lock" }}
            - pip-packages-{{ .Branch }}-
      - run: sudo apt-get update
      - run: sudo apt-get install -y python3-venv
      - run: make init-circle-venv
      - save_cache:
          key: pip-packages-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run: make test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: htmlcov
