version: 2
jobs:
  build:
    working_directory: ~/circleci-deneb
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: make init-venv
      - run:
          name: pytest
          command: make test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: htmlcov
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "/home/circleci/.local/share/virtualenvs/circleci-deneb-ZS5KoU3r"
