version: 2.1

executors:
  py-executor:
    docker:
      - image: circleci/python:3.7.0

jobs:
  build:
    executor: py-executor
    steps:
      - checkout
      - restore_cache:
          key: deps9-{{ .Branch }}
      - run: sudo apt-get update
      - run: sudo apt-get install -y python3-venv
      - run: make init-circle-venv
      - save_cache:
          key: deps9-{{ .Branch }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run: make test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: htmlcov
