version: 2.1

executors:
  py-executor:
    docker:
      - image: circleci/python:3.8.0

jobs:
  build:
    executor: py-executor
    steps:
      - checkout
      - restore_cache:
          key: deps9-{{ checksum "poetry.lock" }}
      - run: make init-circle-venv
      - save_cache:
          key: deps9-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
            - /home/circleci/.cache/pip
      - run: make test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: htmlcov
